Resources:
    LambdaLayer1:
      Type: "AWS::Lambda::LayerVersion"
      Properties:
        CompatibleRuntimes: 
          - python3.8
        Content: 
          S3Bucket: layer456
          S3Key: python.zip
        Description: My layer
        LayerName: Redshift
